name: Pack Workflow
on:
    push:
      branches: [ main ]
      paths-ignore:
        - 'README.md'
    pull_request:    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create compressed file
      run: npm install crx && crx pack -o EDA-time-statistics.crx

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Upload compressed file
      uses: actions/upload-artifact@v4
      with:
        name: project-artifact
        path: EDA-time-statistics.crx